name: JishoTangoAssistant Build and Upload
on: 
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"
      - "README.md"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        dotnet-version: ['9.0']
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build JishoTangoAssistant --no-restore --configuration Release --property:OutputPath=build/JishoTangoAssistant
      - name: Test
        run: dotnet test --no-restore --configuration Release --verbosity normal --property:TestResultsDirectory=build/tests
      - name: Publish (Windows)
        run: dotnet publish JishoTangoAssistant --no-restore --configuration Release --runtime win-x64 --property:PublishDir=publish/win-x64
      - name: Upload to artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: JishoTangoAssistant.exe
          path: ./JishoTangoAssistant/publish/win-x64/JishoTangoAssistant.exe
        if: matrix.os == 'windows-latest'
      - name: Publish (Linux)
        run: dotnet publish JishoTangoAssistant --no-restore --configuration Release --runtime linux-x64 --property:PublishDir=publish/linux-x64
      - name: Upload to artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: JishoTangoAssistant
          path: ./JishoTangoAssistant/publish/linux-x64/JishoTangoAssistant