name: JishoTangoAssistant Build
on: 
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['9.0']
        runtime: ["win-x64", "linux-x64"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build JishoTangoAssistant --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-restore --configuration Release --verbosity normal
      - name: Publish for ${{ matrix.runtime }}
        run: dotnet publish JishoTangoAssistant --no-restore --configuration Release --runtime ${{ matrix.runtime }} --property:PublishDir=publish/${{ matrix.runtime }}
      - name: Upload artifact for ${{ matrix.runtime }}
        uses: actions/upload-artifact@v4
        with:
          name: JishoTangoAssistant-${{ matrix.runtime }}
          path: ./JishoTangoAssistant/publish/${{ matrix.runtime }}/JishoTangoAssistant${{ matrix.runtime == 'win-x64' && '.exe' || '' }}